Tube.am/ViewModels/AddToPlaylistPartialViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Tube.am.Absract.Models;
using Tube.am.DAL.Managers;

namespace Tube.am.ViewModels
{
    public class AddToPlaylistPartialViewModel
    {
        public VideoModel Video { get; set; }

        public UserModel LoggedInUser { get; set; }

        public List<PlaylistModel> UserPlaylists { get; set; }

        public AddToPlaylistPartialViewModel()
        {
            Video = new VideoModel();
            LoggedInUser = UserModelView.LoggedInUser;

            if (LoggedInUser.Id == null)
                UserPlaylists = new List<PlaylistModel>();
            else
                UserPlaylists = PlaylistManager.GetUserPlaylists(LoggedInUser.Id);
        }
    }
}

Tube.am/ViewModels/VideoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Tube.am.Absract.Models;

namespace Tube.am.ViewModels
{
    public class VideoViewModel : GlobalViewModel
    {
        public bool MyPage { get; set; }

        public bool LoggedIn { get; set; }

        public bool IsSubscribed { get; set; }

        public VideoModel Video { get; set; }

        public bool IsPlaylist { get; set; }

        public PlaylistModel Playlist { get; set; }

        public List<VideoModel> RelatedVideos { get; set; }

        public VideoViewModel()
        {
            MyPage = false;
            LoggedIn = false;
            IsSubscribed = false;
            Video = new VideoModel();
            RelatedVideos = new List<VideoModel>();
        }
    }
}

Tube.am/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tube.am.Absract.Models;
using Tube.am.DAL.Managers;
using Tube.am.ViewModels;

namespace Tube.am.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            IndexViewModel model = new IndexViewModel();

            model.Page = "home";

            return View(model);
        }

        public ActionResult Video(int id, int playlistId = 0)
        {
            VideoViewModel model = new VideoViewModel();

            UserModel loggedInUser = UserModelView.LoggedInUser; ;

            model.Video = VideoManager.GetVideoById(id);

            UserModel channel = UserManager.GetUserById(model.Video.Channel.Id);

            if (loggedInUser.Id != null)
            {
                model.LoggedIn = true;

                if (loggedInUser.Id == channel.Id)
                    model.MyPage = true;
                else
                {
                    model.IsSubscribed = false;

                    if (UserManager.GetUsersSubscribedChannels(loggedInUser.Id).Any(x => x.Id == channel.Id))
                        model.IsSubscribed = true;
                }

                UserManager.AddVideoToHistory(loggedInUser.Id, id);
            }

            model.RelatedVideos = VideoManager.GetRelatedVideos(id, loggedInUser.Id);

            if (playlistId != 0)
            {
                model.IsPlaylist = true;
                model.Playlist = PlaylistManager.GetPlaylistById(playlistId);
            }
            else
            {
                model.IsPlaylist = false;
            }

            return View(model);
        }

        public ActionResult LikeDislikeVideo(bool type, int videoId, string userId)
        {
            if (videoId <= 0 || String.IsNullOrEmpty(userId))
                return Redirect("/Home/Video?id=" + videoId);

            VideoManager.LikeDislikeVideo(videoId, userId, type);

            return PartialView("LikeDislikeSectionPartialView", new LikeDislikePartialViewModel() { Video = VideoManager.GetVideoById(videoId) });
        }

        public ActionResult AddToPlaylist(int playlistId, int videoId)
        {
            if (videoId <= 0 || playlistId <= 0)
                return Redirect("/Home/Video?id=" + videoId);

            VideoManager.AddVideoToPlaylists(videoId, playlistId);

            return PartialView("AddToPlaylistPartialView", new AddToPlaylistPartialViewModel() { Video = VideoManager.GetVideoById(videoId) });
        }

        public ActionResult AddToWatchLater(int videoId, string userId)
        {
            if (videoId <= 0 || String.IsNullOrEmpty(userId))
                return Redirect("/Home/Video?id=" + videoId);

            VideoManager.AddVideoToWatchLater(videoId, userId);

            return PartialView("AddToPlaylistPartialView", new AddToPlaylistPartialViewModel() { Video = VideoManager.GetVideoById(videoId) });
        }

        public ActionResult AddNewPlaylist(string playlistName, string userId, int videoId)
        {
            if (String.IsNullOrEmpty(playlistName) || String.IsNullOrEmpty(userId))
                return Redirect("/Home/Video?id=" + videoId);

            PlaylistManager.AddPlaylistForUser(userId, playlistName, videoId);

            return PartialView("AddToPlaylistPartialView", new AddToPlaylistPartialViewModel() { Video = VideoManager.GetVideoById(videoId), LoggedInUser = UserModelView.LoggedInUser });
        }
    }
}

Tube.am/Controllers/ProfileController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Tube.am.Infrastructure;
using Tube.am.Models;
using Tube.am.ViewModels;

namespace Tube.am.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private AppSignInManager _signInManager;

        public ProfileController()
        {
        }

        public ProfileController(AppSignInManager signInManager)
        {
            SignInManager = signInManager;
        }

        public AppSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<AppSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        // GET: Account
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            AccountViewModel.LoginModel model = new AccountViewModel.LoginModel();
            model.Page = "";
            ViewBag.returnUrl = returnUrl;
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(AccountViewModel.LoginModel details, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                AppUser user = await UserManager.FindAsync(details.Email, details.Password);
                if (user == null)
                {
                    details.LoginError = "Error";
                    details.RegisterError = "";
                    ModelState.AddModelError("", "Invalid name or password.");
                }
                else
                {
                    ClaimsIdentity ident = await UserManager.CreateIdentityAsync(user,
                    DefaultAuthenticationTypes.ApplicationCookie);
                    AuthManager.SignOut();
                    AuthManager.SignIn(new AuthenticationProperties
                    {
                        IsPersistent = true
                    }, ident);

                    if (String.IsNullOrEmpty(returnUrl))
                        return Redirect("../Home/Index");
                    else
                        return Redirect(returnUrl);
                }
            }
            ViewBag.returnUrl = returnUrl;
            return View(details);
        }

        //
        // GET: /Account/Register
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new AppUser {
                    NameSurename = model.NameSurename,
                    UserName = model.Email,
                    Email = model.Email,
                    RegistrationDate = DateTime.Now,
                    ChannelName = model.NameSurename,
                    ChannelImageLink = "/Content/channelImages/placeholder.png",
                    ChannelImageAlt = model.NameSurename,
                    ChannelCoverImageLink = "/Content/channelImages/placeholder-cover.png",
                    ChannelCoverImageAlt = model.NameSurename
                };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    //UserManager.Update(user); //optional

                    await SignInManager.SignInAsync(user, isPersistent: true, rememberBrowser: false);

                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("Index", "Home");
                }
                AddErrors(result);
            }

            AccountViewModel.LoginModel modela = new AccountViewModel.LoginModel();
            modela.RegisterError = "Error";
            modela.LoginError = "";

            // If we got this far, something failed, redisplay form
            return View("Login", modela);
        }

        public async Task<ActionResult> Logout()
        {
            AppUser user = await UserManager.FindByNameAsync(HttpContext.User.Identity.Name);
            //MyHdList.Managers.UserManager.ResetUsersLastLogoutDate(user.Id);
            AuthManager.SignOut();
            return RedirectToAction("Index", "Home");
        }

        #region Helpers
        // Used for XSRF protection when adding external logins
        private const string XsrfKey = "XsrfId";

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        internal class ChallengeResult : HttpUnauthorizedResult
        {
            public ChallengeResult(string provider, string redirectUri)
                : this(provider, redirectUri, null)
            {
            }

            public ChallengeResult(string provider, string redirectUri, string userId)
            {
                LoginProvider = provider;
                RedirectUri = redirectUri;
                UserId = userId;
            }

            public string LoginProvider { get; set; }
            public string RedirectUri { get; set; }
            public string UserId { get; set; }

            public override void ExecuteResult(ControllerContext context)
            {
                var properties = new AuthenticationProperties { RedirectUri = RedirectUri };
                if (UserId != null)
                {
                    properties.Dictionary[XsrfKey] = UserId;
                }
                context.HttpContext.GetOwinContext().Authentication.Challenge(properties, LoginProvider);
            }
        }


        private IAuthenticationManager AuthManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }
        #endregion
    }
}

Tube.am/Views/Home/AddToPlaylistPartialView.cshtml
@using Tube.am.ViewModels
@model  AddToPlaylistPartialViewModel

    @{
        ViewBag.Title = "Video";
    }

    <span class="title">Ավելացնել</span>
    <ul class="playlist clear">
        <li>
            @if (Model.LoggedInUser.Id == null)
            {
                <a href="/Profile/Login" target="_blank">
                    <i class="fa fa-clock-o"></i>
                    Դիտել ավելի ուշ
                </a>
            }
            else
            {
                <a href="javascript:void(0)" onclick="javascritp:addToWatchLater(@Model.Video.Id, '@Model.LoggedInUser.Id')">
                    <i class="fa fa-clock-o"></i>
                    Դիտել ավելի ուշ
                </a>
            }
        </li>
        @foreach (var item in Model.UserPlaylists)
        {
            <li>
                <a href="javascript:void(0)" onclick="javascript:addToPlaylist(@item.Id, @Model.Video.Id)">@item.Name</a>
            </li>
        }
        <li class="new">

        </li>
    </ul>
    <div class="new">
        @if (Model.LoggedInUser.Id != null)
        {
            <button onclick="javascript:addNewPlaylist($('#plName').val(), '@Model.LoggedInUser.Id', @Model.Video.Id)">+</button>
        }
        else
        {
            <button onclick="javascript:window.open('/Profile/Login', '_blank')">+</button>
        }
        <input id="plName" type="text" placeholder="Ավելացնել նորը" />
    </div>

Tube.am/Views/Home/LikeDislikeSectionPartialView.cshtml
@using Tube.am.ViewModels
@model LikeDislikePartialViewModel

@{
    ViewBag.Title = "Video";
}

@{
    int likePercent = 100;
    int dislikePercent = 100;
    if (Model.Video.LikesCount == 0)
    {
        likePercent = 0;
    }
    if (Model.Video.DislikesCount == 0)
    {
        dislikePercent = 0;
    }

    int total = Model.Video.LikesCount + Model.Video.DislikesCount;

    if (total == 0)
    {
        total = 1;
    }

    likePercent = (int)Math.Ceiling((decimal)(Model.Video.LikesCount) * 100 / total);
    dislikePercent = (int)Math.Floor((decimal)(Model.Video.DislikesCount) * 100 / total);
}

<div>
    <span>@String.Format("{0:n0}", Model.Video.ViewCount)</span>
    <div class="like">
        <div class="hands">
            @if (Model.LoggedInUser.Id != null)
            {
                <a href="javascript:void(0)" onclick="likeDislikeVideo(true,@(Model.Video.Id),'@Model.LoggedInUser.Id')" class="like">
                    <i class="fa fa-thumbs-o-up"></i>
                    @Model.Video.LikesCount
                </a>
                <a href="javascript:void(0)" onclick="likeDislikeVideo(false,@(Model.Video.Id),'@Model.LoggedInUser.Id')" class="dislike">
                    @Model.Video.DislikesCount
                    <i class="fa fa-thumbs-o-up"></i>
                </a>
            }
            else
            {
                <a href="/Profile/Login" target="_blank" class="like">
                    <i class="fa fa-thumbs-o-up"></i>
                    @Model.Video.LikesCount
                </a>
                <a href="/Profile/Login" target="_blank" class="dislike">
                    @Model.Video.DislikesCount
                    <i class="fa fa-thumbs-o-up"></i>
                </a>
            }
        </div>
        <div class="bar">
            <div class="liked" style="width: @(likePercent)%"></div>
            <div class="dislike" style="width: @(dislikePercent)%"></div>
        </div>
    </div>
</div>

Tube.am/Views/Home/Video.cshtml
@using Tube.am.ViewModels
@model VideoViewModel

@{
    ViewBag.Title = "Video";
}

<div id="content" class="videos col-md-10 col-sm-9 col-xs-12">
    <div id="player" class="block">
        <h1 class="title">@Model.Video.Name</h1>
        <div class="player_section col-md-9">
            <div id="player_holder"></div>
        </div>
        <div class="info col-md-3">
            <div class="channel col-md-12 col-xs-12">
                <div class="thumb col-md-12 col-xs-6">
                    <a class="img" href="/Channel/Index?id=@Model.Video.Channel.Id">
                        <img src="@Model.Video.Channel.ChannelImageLink" alt="@Model.Video.Channel.ChannelImageAlt">
                    </a>
                    <a class="title" href="/Channel/Index?id=@Model.Video.Channel.Id">@Model.Video.Channel.ChannelName</a>
                    <div class="clear"></div>
                    @if (!Model.MyPage)
                    {
                        if (Model.LoggedIn)
                        {
                            if (Model.IsSubscribed)
                            {
                                <button onclick="unsubscribe('@UserModelView.LoggedInUser.Id', '@Model.Video.Channel.Id')" class="button subscribed"><i class="fa fa-times-circle"></i><i class="fa fa-check-circle"></i> Բաժանորդագրված եք </button>
                            }
                            else
                            {
                                <button onclick="subscribe('@UserModelView.LoggedInUser.Id', '@Model.Video.Channel.Id')" class="button"><i class="fa fa-times-circle"></i><i class="fa fa-check-circle"></i> Բաժանորդագրվել </button>
                            }
                        }
                        else
                        {
                            <button onclick="window.location.href = '@Url.Action("Login","Profile")'" class="button"><i class="fa fa-times-circle"></i><i class="fa fa-check-circle"></i> Բաժանորդագրվել </button>
                        }
                    }
                </div>
                <div class="views section col-md-12 col-xs-6 hidden-md hidden-lg">
                    @Html.Partial("LikeDislikeSectionPartialView", new LikeDislikePartialViewModel() { Video = Model.Video })
                </div>
            </div>

            <div class="section col-md-12 col-xs-6">
                <span class="title">Կիսվել</span>
                <ul class="share clear">
                    <li>
                        <a href="#">
                            <i class="fa fa-facebook-official"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-facebook-official"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-facebook-official"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-facebook-official"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-facebook-official"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="section lists col-md-12 col-xs-6">
                @Html.Partial("AddToPlaylistPartialView", new AddToPlaylistPartialViewModel() { Video = Model.Video, LoggedInUser = UserModelView.LoggedInUser })
            </div>
            <div class="views section col-md-12 hidden-xs hidden-sm">
                @Html.Partial("LikeDislikeSectionPartialView", new LikeDislikePartialViewModel() { Video = Model.Video })
            </div>
        </div>
        @if (Model.IsPlaylist)
        {
            <div class="playlist_items col-xs-12">
                <h2 class="title">
                    @Model.Playlist.Name @(Model.Playlist.Videos.Select(x => x.Id).ToList().IndexOf(Model.Video.Id) + 1)/@Model.Playlist.Videos.Count
                </h2>
                <h5 class="title">
                    <a href="/Channel/Index?id=@Model.Playlist.Channel.Id">@Model.Playlist.Channel.ChannelName</a>
                </h5>
                <div class="videos">
                    @foreach (var item in Model.Playlist.Videos)
                    {
                        <div class="video col-md-3 col-sm-4 col-xs-6">
                            <a href="/Home/Video?id=@(item.Id)&playlistId=@Model.Playlist.Id" class="thumb aspect">
                                <img src="@item.ThumbnailImageLink" alt="@item.ThumbnailImageAlt">
                                @if (item.Duration.Hours > 0)
                                {
                                    <div class="duration">@(item.Duration.ToString(@"hh\:mm\:ss"))</div>
                                }
                                else
                                {
                                    <div class="duration">@(item.Duration.ToString(@"mm\:ss"))</div>
                                }
                            </a>
                            <div class="info_holder">
                                <a href="/Home/Video?id=@(item.Id)&playlistId=@Model.Playlist.Id" class="title">@item.Name</a>
                                <div class="info">
                                    <a href="/Channel/Index?id=@item.Channel.Id" class="channel">@item.Channel.ChannelName</a>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
        <div class="description col-xs-12">
            <h2 class="title">
                Նկարագրություն
            </h2>
            <p>
                @Model.Video.Description
                <div class="expand">Show more</div>
            </p>
        </div>
    </div>

    <h2 class="title">
        Related Videos
    </h2>
    <div class="block">
        @foreach (var item in Model.RelatedVideos)
        {
            <div class="video col-md-3 col-sm-4 col-xs-6">
                <a href="/Home/Video?id=@item.Id" class="thumb aspect">
                    <img src="@item.ThumbnailImageLink" alt="@item.ThumbnailImageAlt">
                    <div class="duration">@(item.Duration.ToString(@"hh\:mm\:ss"))</div>
                </a>
                <div class="info_holder">
                    <a href="/Home/Video?id=@item.Id" class="title">@item.Name</a>
                    <div class="info">
                        <a href="/Channel/Index?id=@item.Channel.Id" class="channel">@item.Channel.ChannelName</a>
                        <span class="views">@String.Format("{0:n0}", item.ViewCount) Դիտում</span>
                        <span class="added">@item.UploadedDate.GetRelativeTime()</span>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script type="text/javascript">
    var playerInstance = jwplayer("player_holder");
    playerInstance.setup({
        image: "//" + window.location.host + "@Model.Video.ThumbnailImageLink.Replace('\\', '/')",
        width: '100%',
        aspectratio: '16:9',
        sources: [{
            file: "//" + window.location.host + "@Model.Video.Link.Replace('\\', '/')",
            label: "480p"
        }, {
            file: "//" + window.location.host + "@Model.Video.Link.Replace('\\', '/')",
            label: "hidden"
        }],
        skin: {
            url: "/Content/cold.css",
            name: "Cold"
        },
        events: {
            onComplete: function () {
                console.log("player on complete");
                @if (Model.IsPlaylist)
                {
                   @: window.location.replace('/Home/Video?id=' + @Model.Video.Id + '&playlistId=' + @Model.Playlist.Id)
                }
            }
        }
    });
</script>